name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Run security tests
      run: |
        cat > test-security.js << 'EOF'
        import { validateLocalUrl } from './dist/utils/security.js';

        const testCases = [
          { url: 'http://localhost:3000', expected: true },
          { url: 'http://127.0.0.1:8080', expected: true },
          { url: 'http://192.168.1.100:3000', expected: true },
          { url: 'http://google.com', expected: false },
          { url: 'https://example.com', expected: false },
          { url: 'ftp://localhost:21', expected: false }
        ];

        let passed = 0;
        testCases.forEach(({ url, expected }) => {
          const result = validateLocalUrl(url);
          if (result.valid === expected) passed++;
        });

        console.log(`Security tests: ${passed}/${testCases.length} passed`);
        if (passed !== testCases.length) process.exit(1);
        console.log('✅ All security tests passed!');
        EOF

        node test-security.js

    - name: Test server startup
      run: |
        timeout 5s node dist/index.js || echo "✅ Server startup test passed"