name: Release and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Test before release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Run tests
      run: |
        cat > test-security.js << 'EOF'
        import { validateLocalUrl } from './dist/utils/security.js';

        const testCases = [
          { url: 'http://localhost:3000', expected: true },
          { url: 'http://127.0.0.1:8080', expected: true },
          { url: 'http://192.168.1.100:3000', expected: true },
          { url: 'http://google.com', expected: false },
          { url: 'https://example.com', expected: false },
          { url: 'ftp://localhost:21', expected: false }
        ];

        let passed = 0;
        testCases.forEach(({ url, expected }) => {
          const result = validateLocalUrl(url);
          if (result.valid === expected) passed++;
        });

        console.log(`Security tests: ${passed}/${testCases.length} passed`);
        if (passed !== testCases.length) process.exit(1);
        console.log('✅ All security tests passed!');
        EOF

        node test-security.js

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Update package.json with author info
      run: |
        npm pkg set author="await29"
        npm pkg set repository.type="git"
        npm pkg set repository.url="git+https://github.com/Await-d/local-request-mcp.git"
        npm pkg set homepage="https://github.com/Await-d/local-request-mcp#readme"
        npm pkg set bugs.url="https://github.com/Await-d/local-request-mcp/issues"

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          🚀 New release of local-request-mcp!

          ## What's Changed
          - Built and tested automatically via GitHub Actions
          - Available on NPM: `npx local-request-mcp`

          ## Usage
          ```bash
          npx local-request-mcp
          ```

          For more information, see the [README](https://github.com/Await-d/local-request-mcp#readme).
        draft: false
        prerelease: false